# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-identifiers]
NSXV3_SUPPRESS_SSL_WORNINGS = "NSXV3_SUPPRESS_SSL_WORNINGS"
WORNINGS = "WORNINGS"

[files]
extend-exclude = [
  "go.mod",
]
